CREATE TABLE PQ_FIND_ENGR_INFO (
  ENGR_ID VARCHAR(30) NOT NULL,
  WORK_DUTY_ID VARCHAR(30) NOT NULL,
  BID_SEQ NUMBER(10) NOT NULL,
  CONSTRAINT PK_PQ_FIND_ENGR_INFO PRIMARY KEY (BID_SEQ, WORK_DUTY_ID, ENGR_ID)
);

COMMENT ON TABLE PQ_FIND_ENGR_INFO IS 'PQ참여 기술자 선정 정보';

COMMENT ON COLUMN PQ_FIND_ENGR_INFO.ENGR_ID IS '엔지니어 id';
COMMENT ON COLUMN PQ_FIND_ENGR_INFO.WORK_DUTY_ID IS 'PQ작업자';
COMMENT ON COLUMN PQ_FIND_ENGR_INFO.BID_SEQ IS '공고문 시퀀스';

CREATE INDEX IX_PQ_FIND_ENGR_INFO_ENGR_ID ON PQ_FIND_ENGR_INFO (ENGR_ID);
CREATE INDEX IX_PQ_FIND_ENGR_INFO_BID_SEQ ON PQ_FIND_ENGR_INFO (BID_SEQ);
