podTemplate(
    yaml: '''
apiVersion: v1
kind: Pod
spec:
  containers:

  - name: backend
    image: amazoncorretto:25-al2023-jre
    command:
      - sleep
    args:
      - 99d
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "3Gi"

  - name: frontend
    image: node:22-alpine
    command:
      - sleep
    args:
      - 99d
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "2"
        memory: "2Gi"
'''
) {

    node(POD_LABEL) {
        stage('Checkout Application') {
            dir('pq-system') {
                git branch: 'main',
                    credentialsId: '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',
                    url: 'https://github.com/lutae2000/pq-system.git'
            }
        }
        stage('Backend Build') {
            container('backend') {
                dir('pq-system/cheil_be') {
                    sh '''
                        chmod +x gradlew
                        ./gradlew clean build
                    '''
                }
            }
        }

        stage('Frontend Build') {
            container('frontend') {
                dir('pq-system/cheil_fe') {
                    sh '''
                        npm ci
                        npm run build
                    '''

                }
            }
        }
    }
}