/*
  신규 고용률 관리 참고 DDL 및 조회 SQL

  API 경로:
  - GET    /api/pq/new-employment-rates/summary
  - GET    /api/pq/new-employment-rates/monthly-statuses
  - GET    /api/pq/new-employment-rates/employees
  - GET    /api/pq/new-employment-rates/employees/{id}
  - POST   /api/pq/new-employment-rates/employees
  - PUT    /api/pq/new-employment-rates/employees/{id}
  - DELETE /api/pq/new-employment-rates/employees/{id}
*/

CREATE TABLE pq_new_employment_employees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  base_year_month CHAR(7) NOT NULL,
  employee_no VARCHAR(30),
  employee_name VARCHAR(100) NOT NULL,
  birth_date CHAR(8),
  hire_date CHAR(8) NOT NULL,
  department_code VARCHAR(30) NOT NULL,
  job_category VARCHAR(100),
  remark VARCHAR(1000),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_id VARCHAR(100),
  last_changed_at TIMESTAMP,
  last_changed_id VARCHAR(100),
  CONSTRAINT uq_pq_new_employment_employee UNIQUE (base_year_month, employee_no, employee_name, hire_date)
);

CREATE INDEX ix_pq_new_employment_employees_01
  ON pq_new_employment_employees (base_year_month, department_code, employee_name);

/* 신규 고용자 목록 */
SELECT
  hire.id,
  hire.base_year_month,
  hire.employee_no,
  hire.employee_name,
  hire.birth_date,
  hire.hire_date,
  hire.department_code,
  dept.dept_name AS department_name,
  hire.job_category,
  hire.remark,
  hire.created_at,
  hire.created_id,
  hire.last_changed_at,
  hire.last_changed_id
FROM pq_new_employment_employees hire
LEFT JOIN department dept
  ON dept.dept_code = hire.department_code
WHERE (:selected_year_month IS NULL OR hire.base_year_month = :selected_year_month)
  AND (:department_code IS NULL OR hire.department_code = :department_code)
  AND (:employee_name IS NULL OR hire.employee_name LIKE '%' || :employee_name || '%')
ORDER BY hire.hire_date DESC, hire.employee_name;

/* 월별 고용현황: monthly_employee_count는 인사 마스터 또는 월별 스냅샷 테이블로 대체 */
SELECT
  months.base_year_month,
  COALESCE(monthly_employee_count.employee_count, 0) AS employee_count,
  COUNT(hire.id) AS new_hire_count,
  CASE
    WHEN COALESCE(monthly_employee_count.employee_count, 0) = 0 THEN NULL
    ELSE COUNT(hire.id) * 100.0 / monthly_employee_count.employee_count
  END AS new_hire_rate
FROM monthly_employee_count
LEFT JOIN pq_new_employment_employees hire
  ON hire.base_year_month = monthly_employee_count.base_year_month
  AND (:department_code IS NULL OR hire.department_code = :department_code)
  AND (:employee_name IS NULL OR hire.employee_name LIKE '%' || :employee_name || '%')
JOIN monthly_employee_count months
  ON months.base_year_month = monthly_employee_count.base_year_month
WHERE monthly_employee_count.base_year_month BETWEEN
  COALESCE(:from_year_month, (SELECT MIN(base_year_month) FROM monthly_employee_count))
  AND COALESCE(:base_year_month, (SELECT MAX(base_year_month) FROM monthly_employee_count))
GROUP BY months.base_year_month, monthly_employee_count.employee_count
ORDER BY months.base_year_month;

/* 더미 데이터 예시: 2024-08 ~ 2026-07, 4개 부서 기준 */
INSERT INTO pq_new_employment_monthly_counts (
  base_year_month,
  department_code,
  employee_count,
  created_id,
  last_changed_id
)
SELECT
  months.base_year_month,
  dept.department_code,
  24 + months.month_index * 2 + dept.department_index,
  'SYSTEM',
  'SYSTEM'
FROM (
  SELECT
    gs AS month_index,
    to_char(date '2024-08-01' + make_interval(months => gs), 'YYYY-MM') AS base_year_month
  FROM generate_series(0, 23) AS gs
) months
CROSS JOIN (
  VALUES
    (0, 'D001'),
    (1, 'D002'),
    (2, 'D003'),
    (3, 'D004')
) dept(department_index, department_code)
WHERE NOT EXISTS (
  SELECT 1
  FROM pq_new_employment_monthly_counts
);

INSERT INTO pq_new_employment_employees (
  base_year_month,
  employee_no,
  employee_name,
  birth_date,
  hire_date,
  department_code,
  job_category,
  remark,
  created_id,
  last_changed_id
)
SELECT
  months.base_year_month,
  format('NE%s%s', months.year_month_key, lpad(dept.department_index::text, 2, '0')) AS employee_no,
  names[((months.month_index + dept.department_index) % array_length(names, 1)) + 1] AS employee_name,
  to_char(date '1986-01-01' + make_interval(days => (months.month_index * 17 + dept.department_index * 29) % 10000), 'YYYYMMDD') AS birth_date,
  to_char(date '2024-08-01' + make_interval(months => months.month_index, days => dept.department_index), 'YYYYMMDD') AS hire_date,
  dept.department_code,
  job_categories[((months.month_index + dept.department_index) % array_length(job_categories, 1)) + 1] AS job_category,
  format('%s월 %s 신입사원', months.base_year_month, dept.department_code) AS remark,
  'SYSTEM',
  'SYSTEM'
FROM (
  SELECT
    gs AS month_index,
    to_char(date '2024-08-01' + make_interval(months => gs), 'YYYY-MM') AS base_year_month,
    to_char(date '2024-08-01' + make_interval(months => gs), 'YYYYMM') AS year_month_key
  FROM generate_series(0, 23) AS gs
) months
CROSS JOIN (
  VALUES
    (0, 'D001'),
    (1, 'D002'),
    (2, 'D003'),
    (3, 'D004')
) dept(department_index, department_code)
CROSS JOIN (
  SELECT ARRAY[
    '홍길동', '김철수', '이영희', '박민수', '최지은', '정수빈',
    '강호준', '한지민', '오세훈', '윤가은', '서민우', '조현아',
    '배준호', '문지아', '손태현', '임수아', '장도윤', '남지우',
    '허서윤', '고예준', '문수진', '안태호', '백하늘', '차민재'
  ] AS names,
  ARRAY[
    '토목', '건축', '기계', '전기', '품질', '안전', '공무', '관리'
  ] AS job_categories
) lookup
WHERE NOT EXISTS (
  SELECT 1
  FROM pq_new_employment_employees
);
