/* This file is generated by scripts/generate-page-registry.mjs.
 * Do not edit manually. It intentionally contains only route path strings
 * so menu/admin code can validate system_menus.menuPath without importing
 * page components.
 */

export const generatedPagePaths = [
  "/code",
  "/code/certifications",
  "/code/clients",
  "/code/common-codes",
  "/code/construction-types",
  "/code/departments",
  "/code/headquarters",
  "/code/service-types",
  "/dashboard",
  "/education-reminders",
  "/education-reminders/basic-infos",
  "/education-reminders/completions",
  "/education-reminders/send-history",
  "/education-reminders/templates",
  "/pq",
  "/pq/bid-notice",
  "/pq/bid-results",
  "/pq/company-performance",
  "/pq/documents/company-performance-docs",
  "/pq/documents/engineer-overlap-check",
  "/pq/documents/engineer-performance-docs",
  "/pq/documents/performance-certificate-engineers",
  "/pq/documents/pq-participating-engineers",
  "/pq/education-reminders",
  "/pq/engineers/performance",
  "/pq/engineers/profile",
  "/pq/new-employment-rates",
  "/pq/new-technology-developments",
  "/pq/new-technology-investments",
  "/pq/new-technology-usages",
  "/pq/partner-order-codes",
  "/pq/qualification-criteria",
  "/pq/service-performance-management",
  "/pq/shinindo-management",
  "/pq/similar-service-performances",
  "/system",
  "/system/menus",
  "/system/notices",
  "/system/policies",
  "/system/roles",
  "/system/user-management",
  "/work-overlap/contracts",
  "/work-overlap/engineers",
] as const;

export type GeneratedPagePath = (typeof generatedPagePaths)[number];
