plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.0'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.asciidoctor.jvm.convert' version '4.0.5'
}

group = 'com.cheil'
version = '0.0.1-SNAPSHOT'
description = 'cheil_be'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

ext {
    set('snippetsDir', file("build/generated-snippets"))
    set('springBootVersion', '4.1.0')
    set('aspectjVersion', '1.9.25.1')
    set('datasourceMicrometerVersion', '1.0.2')
    set('flywayVersion', '12.4.0')
    set('gsonVersion', '2.13.1')
    set('jakartaAnnotationVersion', '3.0.0')
    set('jakartaPersistenceVersion', '3.2.0')
    set('junitPlatformVersion', '1.13.4')
    set('lombokVersion', '1.18.46')
    set('micrometerVersion', '1.17.0')
    set('pdfboxVersion', '2.0.31')
    set('p6spyVersion', '3.9.1')
    set('postgresqlVersion', '42.7.11')
    set('querydslVersion', '5.1.0')
    set('restDocsVersion', '4.0.1')
}

dependencies {
    implementation "org.springframework.boot:spring-boot-starter-actuator:${springBootVersion}"
    implementation "org.springframework.boot:spring-boot-starter-data-jpa:${springBootVersion}"
    implementation "org.springframework.boot:spring-boot-starter-data-redis:${springBootVersion}"
    implementation "org.springframework.boot:spring-boot-starter-json:${springBootVersion}"
    implementation "org.springframework.boot:spring-boot-starter-mail:${springBootVersion}"
    implementation "org.springframework.boot:spring-boot-starter-security:${springBootVersion}"
    implementation "org.springframework.boot:spring-boot-starter-webmvc:${springBootVersion}"
    implementation "org.springframework.boot:spring-boot-starter-opentelemetry:${springBootVersion}"
    implementation "org.apache.pdfbox:pdfbox:${pdfboxVersion}"
    implementation "net.ttddyy.observation:datasource-micrometer:${datasourceMicrometerVersion}"
    implementation "org.aspectj:aspectjweaver:${aspectjVersion}"
    implementation "com.google.code.gson:gson:${gsonVersion}"
    implementation "p6spy:p6spy:${p6spyVersion}"
    implementation "com.querydsl:querydsl-jpa:${querydslVersion}:jakarta"
    implementation "org.flywaydb:flyway-core:${flywayVersion}"
    implementation "org.flywaydb:flyway-database-postgresql:${flywayVersion}"
    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    developmentOnly "org.springframework.boot:spring-boot-devtools:${springBootVersion}"
    developmentOnly "org.springframework.boot:spring-boot-docker-compose:${springBootVersion}"
    runtimeOnly "io.micrometer:micrometer-registry-prometheus:${micrometerVersion}"
    runtimeOnly "org.postgresql:postgresql:${postgresqlVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "com.querydsl:querydsl-apt:${querydslVersion}:jakarta"
    annotationProcessor "jakarta.persistence:jakarta.persistence-api:${jakartaPersistenceVersion}"
    annotationProcessor "jakarta.annotation:jakarta.annotation-api:${jakartaAnnotationVersion}"
    testImplementation "org.springframework.boot:spring-boot-starter-actuator-test:${springBootVersion}"
    testImplementation "org.springframework.boot:spring-boot-starter-data-jpa-test:${springBootVersion}"
    testImplementation "org.springframework.boot:spring-boot-starter-data-redis-test:${springBootVersion}"
    testImplementation "org.springframework.boot:spring-boot-starter-restdocs:${springBootVersion}"
    testImplementation "org.springframework.boot:spring-boot-starter-security-test:${springBootVersion}"
    testImplementation "org.springframework.boot:spring-boot-starter-webmvc-test:${springBootVersion}"
    testImplementation "org.springframework.restdocs:spring-restdocs-mockmvc:${restDocsVersion}"
    testImplementation "com.google.code.gson:gson:${gsonVersion}"
    testCompileOnly "org.projectlombok:lombok:${lombokVersion}"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher:${junitPlatformVersion}"
    testAnnotationProcessor "org.projectlombok:lombok:${lombokVersion}"
}

def querydslDir = layout.buildDirectory.dir("generated/querydsl").get().asFile

sourceSets {
    main.java.srcDirs += querydslDir
}

tasks.withType(JavaCompile).configureEach {
    options.generatedSourceOutputDirectory = file(querydslDir)
}

tasks.named('test') {
    outputs.dir snippetsDir
    useJUnitPlatform()
}

tasks.named('asciidoctor') {
    inputs.dir snippetsDir
    dependsOn test
    attributes 'snippets': snippetsDir
    baseDirFollowsSourceFile()
}

tasks.named('bootJar') {
    dependsOn tasks.named('asciidoctor')
    from(layout.buildDirectory.dir('docs/asciidoc')) {
        into 'BOOT-INF/classes/static/docs'
    }
}
