/*

  API 경로:
  - GET    /api/pq/service-performance-management
  - GET    /api/pq/service-performance-management/{id}
  - POST   /api/pq/service-performance-management
  - PUT    /api/pq/service-performance-management/{id}
  - DELETE /api/pq/service-performance-management/{id}

*/

CREATE TABLE service_performances (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 client_code VARCHAR(30) NOT NULL,
 field_name VARCHAR(100) NOT NULL,
 site_name VARCHAR(200) NOT NULL,
 evaluation_date CHAR(8) NOT NULL,
 service_amount NUMERIC(15,2),
 evaluation_score NUMERIC(6,2),
 remark VARCHAR(1000),
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 created_id VARCHAR(100),
 last_changed_at TIMESTAMP,
 last_changed_id VARCHAR(100)
);

COMMENT ON TABLE service_performances IS '용역 수행성과 관리';
COMMENT ON COLUMN service_performances.id IS '고유 식별자';
COMMENT ON COLUMN service_performances.client_code IS '발주처 코드';
COMMENT ON COLUMN service_performances.field_name IS '분야';
COMMENT ON COLUMN service_performances.site_name IS '현장명';
COMMENT ON COLUMN service_performances.evaluation_date IS '평가일자';
COMMENT ON COLUMN service_performances.service_amount IS '용역금액';
COMMENT ON COLUMN service_performances.evaluation_score IS '평가점수';
COMMENT ON COLUMN service_performances.remark IS '비고';
COMMENT ON COLUMN service_performances.created_at IS '등록일시';
COMMENT ON COLUMN service_performances.created_id IS '등록자';
COMMENT ON COLUMN service_performances.last_changed_at IS '수정일시';
COMMENT ON COLUMN service_performances.last_changed_id IS '수정자';

CREATE INDEX ix_service_performances_01
  ON service_performances (evaluation_date, client_code, field_name);

CREATE INDEX ix_service_performances_02
  ON service_performances (site_name);

/* 목록 조회 */
SELECT
  p.id,
  p.client_code,
  p.client_code AS client_name,
  p.evaluation_score AS amount_reflected_evaluation_score,
  p.field_name,
  p.site_name,
  p.evaluation_date,
  p.service_amount,
  p.evaluation_score,
  p.remark,
  p.created_at,
  p.created_id,
  p.last_changed_at,
  p.last_changed_id
FROM service_performances p
WHERE (:client_code IS NULL OR p.client_code = :client_code)
  AND (:field_name IS NULL OR p.field_name LIKE '%' || :field_name || '%')
  AND (:site_name IS NULL OR p.site_name LIKE '%' || :site_name || '%')
  AND (:keyword IS NULL OR (
    p.field_name LIKE '%' || :keyword || '%'
    OR p.site_name LIKE '%' || :keyword || '%'
    OR p.client_code LIKE '%' || :keyword || '%'
  ))
  AND (:reference_date IS NULL OR
    p.evaluation_date <= :reference_date
    AND (
      :period_type = 'ALL'
      OR p.evaluation_date >= CASE
        WHEN :period_type = '3' THEN to_char((to_date(:reference_date, 'YYYYMMDD') - INTERVAL '3 years')::date, 'YYYYMMDD')
        WHEN :period_type = '5' THEN to_char((to_date(:reference_date, 'YYYYMMDD') - INTERVAL '5 years')::date, 'YYYYMMDD')
        ELSE '00000000'
      END
    )
  )
ORDER BY p.evaluation_date DESC, p.id DESC;

/* 상세 조회 */
SELECT
  p.id,
  p.client_code,
  p.client_code AS client_name,
  p.evaluation_score AS amount_reflected_evaluation_score,
  p.field_name,
  p.site_name,
  p.evaluation_date,
  p.service_amount,
  p.evaluation_score,
  p.remark,
  p.created_at,
  p.created_id,
  p.last_changed_at,
  p.last_changed_id
FROM service_performances p
WHERE p.id = :id;

/* 등록 */
INSERT INTO service_performances (
  client_code,
  field_name,
  site_name,
  evaluation_date,
  service_amount,
  evaluation_score,
  remark,
  created_id,
  last_changed_id
) VALUES (
  :client_code,
  :field_name,
  :site_name,
  :evaluation_date,
  :service_amount,
  :evaluation_score,
  :remark,
  :created_id,
  :last_changed_id
);

/* 수정 */
UPDATE service_performances
SET
  client_code = :client_code,
  field_name = :field_name,
  site_name = :site_name,
  evaluation_date = :evaluation_date,
  service_amount = :service_amount,
  evaluation_score = :evaluation_score,
  remark = :remark,
  last_changed_at = CURRENT_TIMESTAMP,
  last_changed_id = :last_changed_id
WHERE id = :id;

/* 삭제 */
DELETE FROM service_performances
WHERE id = :id;

