
appender=com.p6spy.engine.spy.appender.Slf4JLogger
logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat
customLogMessageFormat=%(currentTime) | %(executionTime)ms | %(effectiveSqlSingleLine)
filter=true
excludeCategories=info,result,resultset,batch,debug
